Repository prgrms-web-devcourse/Team_DOKEV_GOLDDDUCK_FE, pull requests merged in 2021-12, with the labels that each got.

#3 [GD-83] feat: 색상, 아이콘, 글자크기 및 default margin 상수화
  src/utils/constants/colors.ts
  src/utils/constants/icons.ts
  src/utils/constants/sizes.ts
Labels: Feat

#2 [GD-65] feat: Image 컴포넌트 구현 및 스토리북 등록
  .storybook/main.js
  src/components/Image/index.tsx
  src/stories/components/image.stories.tsx
Labels: Feat, 피드백 반영 && 리뷰 재요청

#7 [GD-66] feat: Input/Test-Radio 컴포넌트 구현 및 스토리북 등록
  src/components/Input/InputRadio.tsx
  src/components/Input/InputText.tsx
  src/components/Input/index.tsx
  src/stories/components/Input.stories.tsx
  src/utils/constants/sizes.ts
Labels: 리뷰 요청, Feat

#5 [GD-76] feat: Icon 컴포넌트 구현
  package.json
  src/components/Icon/index.tsx
  src/stories/components/Icon.stories.tsx
  tsconfig.extend.json
  yarn.lock
Labels: 리뷰 요청, Feat

#10 [GD-91] feat: Textarea 컴포넌트 구현 및 스토리북 등록
  src/components/Textarea/index.tsx
  src/stories/components/Textarea.stories.tsx
Labels: 리뷰 요청, Feat

#6 [GD-77] feat: Spinner 컴포넌트 구현
  src/components/Spinner/index.tsx
  src/stories/components/Spinner.stories.tsx
Labels: 리뷰 요청, Feat

#8 [GD-63] feat: MUIAvatar 컴포넌트 및 storybook 구현
  pages/test.tsx
  src/components/MUIAvatar/index.tsx
  src/stories/Avtar.stories.tsx
Labels: 리뷰 요청, Feat

#9 [GD-75] feat: Timer 컴포넌트 구현
  src/components/Timer/index.tsx
  src/stories/components/Icon.stories.tsx
  src/stories/components/Input.stories.tsx
  src/stories/components/Spinner.stories.tsx
  src/stories/components/Timer.stories.tsx
  src/utils/formatTimeNumber.ts
Labels: 리뷰 요청, Feat

#17 [GD-57] feat: Fifo 페이지 기초 레이아웃 구현
  pages/Fifo.tsx
  src/domains/Header/index.tsx
Labels: 리뷰 요청, Feat

#13 [GD-62] feat: Logo 컴포넌트 및 스토리북 구현
  .storybook/preview.js
  pages/testPagePartro.tsx
  public/logo.png
  src/components/Logo/index.tsx
  src/stories/components/Logo.stories.tsx
Labels: 리뷰 요청, Feat

#24 [GD-106] feat: useLocalStorage Hook 추가
  src/hooks/useLocalStorage.tsx
Labels: 리뷰 요청, Feat

#20 [GD-68] feat: Upload 컴포넌트 구현 및 스토리북 등록
  src/components/Upload/index.tsx
  src/stories/components/Upload.stories.tsx
Labels: 리뷰 요청, Feat

#23 chore : MUI Button Props 추가, onClick 이벤트 type 지정
  src/components/MUIButton/index.tsx
Labels: 리뷰 요청

#22 [GD-56] feat: post 페이지 stepper 구현
  .eslintrc.json
  pages/post.tsx
  styles/globals.css
Labels: 리뷰 요청, Feat

#26 [GD-110] feat: Header 도메인 컴포넌트 구현 및 스타일
  pages/index.tsx
  src/components/Image/index.tsx
  src/components/Logo/index.tsx
  src/components/MUIAvatar/index.tsx
  src/domains/Header/index.tsx
  src/stories/components/Avtar.stories.tsx
Labels: Feat

#19 [GD-74] feat: Modal 컴포넌트 구현 및 스토리북 테스트
  .storybook/preview.js
  pages/_app.tsx
  src/components/Icon/index.tsx
  src/components/Modal/index.tsx
  src/stories/components/ConfirmModal.stories.tsx
  src/stories/components/Modal.stories.tsx
Labels: 리뷰 요청, Feat

#30 [GD-113] chore: fifo 라우터 변경에 따른 디렉토리 구조 변경
  pages/fifo/[url].tsx
Labels: 리뷰 요청, Refactor

#27 [GD-103] feat: Login 페이지 CSS 적용 & Text 컴포넌트 불필요 로직 삭제
  pages/login.tsx
  public/google.png
  public/video/Snow.mp4
Labels: Feat, 피드백 반영 && 리뷰 재요청

#25 [GD]102] feat: UserProvider Context API 기능 구현
  pages/_app.tsx
  pages/testPageMuntari.tsx
  src/contexts/UserProvider.tsx
Labels: 리뷰 요청, Feat, 피드백 반영 && 리뷰 재요청

#21 [GD-55] feat: mypage 레이아웃 및 라우팅
  pages/mypage/MUITab.tsx
  pages/mypage/MUITabPanel.tsx
  pages/mypage/index.tsx
Labels: Feat, 피드백 반영 && 리뷰 재요청

#34 [GD-119] refactor: Image 지연로딩 기능 삭제
  src/components/Image/index.tsx
  src/stories/components/image.stories.tsx
Labels: Refactor

#31 [GD-112] feat: TimerHeader 도메인 컴포넌트 구현 및 Sizes LARGER 추가
  pages/fifo/[url].tsx
  src/domains/TimerHeader/index.tsx
  src/utils/constants/sizes.ts
Labels: Feat, 피드백 반영 && 리뷰 재요청

#35 [GD-55] fix: mypage SSR warning 해결
  pages/mypage.tsx
  src/components/MUITab/MUITab.tsx
  src/components/MUITab/MUITabPanel.tsx
  src/domains/Header/index.tsx
Labels: Fix

#32 [GD-60] feat: gift detailpage 레이아웃 및 라우팅
  pages/gift/[id].tsx
  src/assets/gift_test.png
Labels: 리뷰 요청, Feat

#36 [GD-124] fix: [Next SSR]ReferenceError localstorage is not defined 에러 해결
  src/hooks/useLocalStorage.tsx
Labels: 리뷰 요청, Fix

#39 [GD-137] chore: Random 페이지 디렉토리 구조 변경
  pages/random/[url].tsx
Labels: Chore

#38 [GD-115] feat: EventTimer domain 개발 (step2)
  package.json
  pages/_app.tsx
  pages/post.tsx
  src/domains/EventTimer/index.tsx
  styles/globals.css
  yarn.lock
Labels: 리뷰 요청, Feat

#40 [GD-126] feat: EventType domain 개발 (step3)
  pages/post.tsx
  public/eventType1.png
  public/eventType2.png
  src/domains/EventTitle/index.tsx
  src/domains/EventType/index.tsx
Labels: 리뷰 요청, Feat

#37 [GD-120] feat: 선물목록 보여주기 기능 구현
  pages/fifo/[url].tsx
  public/EventOver.png
  src/components/Timer/index.tsx
  src/domains/TimerHeader/index.tsx
Labels: 리뷰 요청, Feat, 피드백 반영 && 리뷰 재요청

#43 [GD-146] feat: SweetAlert2 패키지 설치 및 Swalert 컴포넌트 구현
  package.json
  public/alert.png
  src/components/Swalert/index.tsx
  src/stories/components/Swalert.stories.tsx
  yarn.lock
Labels: 리뷰 요청, Feat

#42 [GD-104] feat: 소셜 로그인 URL 설정 및 Oauth 페이지 추가
  pages/login.tsx
  pages/oauth/redirect.tsx
  public/kakao.png
  src/contexts/UserProvider.tsx
Labels: Feat, 피드백 반영 && 리뷰 재요청

#46 [GD-59] feat: eventpage 레이아웃 및 스타일
  pages/event/Cover.tsx
  pages/event/TimeInfo.tsx
  pages/event/WinnerModal.tsx
  pages/event/[id].tsx
  src/components/Modal/index.tsx
  src/components/Timer/index.tsx
  src/types/event.d.ts
  src/utils/constants/icons.ts
Labels: 리뷰 요청, Feat

#44 [GD-139] feat: EventType domain 개발 (step4)
  pages/post.tsx
  public/nothing.png
  src/domains/EventPresent/index.tsx
  src/utils/constants/icons.ts
Labels: 리뷰 요청, Feat

#50 [GD-153] feat: 체크박스 컴포넌트 및 체크박스 리스트 구현
  src/components/Checkbox/index.tsx
  src/domains/CheckboxList/index.tsx
  src/stories/components/Checkbox.stories.tsx
Labels: Feat

#53 [GD-159] feat: API 모듈화 작업
  pages/api/services/user.ts
  pages/api/user.ts
  pages/api/utils/index.ts
Labels: Feat

#56 [GD-105] feat: getUserData API 구현 및 ContextAPI 연동
  pages/api/user.ts
  pages/api/utils/index.ts
  pages/index.tsx
  pages/oauth/redirect.tsx
  src/components/MUIAvatar/index.tsx
  src/contexts/UserProvider.tsx
  src/domains/Header/index.tsx
Labels: Feat

#54 [GD-157] feat: GiftItem 도메인 컴포넌트 구현
  public/templates/template1.png
  public/templates/template2.png
  public/templates/template3.png
  public/templates/template4.png
  public/templates/template5.png
  public/templates/template6.png
  src/domains/GiftItem/index.tsx
  src/types/event.d.ts
  src/types/gift.d.ts
Labels: 리뷰 요청, Feat

#57 [GD-169] feat: logout 기능 구현
  src/utils/logOut.ts
Labels: 리뷰 요청, Feat

#51 [GD-147] feat: 선물 등록 모달 폼 EventPresentModal domain 개발 (step4-1)
  .eslintrc.json
  package.json
  pages/post.tsx
  src/components/Input/InputText.tsx
  src/components/Modal/index.tsx
  src/components/Textarea/index.tsx
  src/components/Upload/index.tsx
  src/domains/EventPresent/GiftForm.tsx
  src/domains/EventPresent/PresentModal.tsx
  src/domains/EventPresent/index.tsx
  yarn.lock
Labels: 리뷰 요청, Feat, 피드백 반영 && 리뷰 재요청

#55 [GD-149] feat: GiftList 컴포넌트 구현
  pages/api/gift.ts
  pages/api/services/gift.ts
  pages/mypage.tsx
  src/assets/used_mark.png
  src/components/Checkbox/index.tsx
  src/components/MUITab/MUITabPanel.tsx
  src/domains/CheckboxList/index.tsx
  src/domains/GiftItem/index.tsx
  src/domains/GiftList.tsx/index.tsx
  src/types/gift.d.ts
Labels: 리뷰 요청, Feat

#52 [GD-148] refactor: Random CSS 및 인터렉션 변경
  pages/random/[url].tsx
  public/GiftRudolf.png
  public/card.jpg
  public/stargif.gif
  public/video/Stars.mp4
  src/domains/CardFlip/index.tsx
Labels: Refactor, 피드백 반영 && 리뷰 재요청

#59 [GD-160] 마이페이지 Event List 구현 및 api 연동
  pages/api/event.ts
  pages/api/services/event.ts
  pages/api/services/gift.ts
  pages/api/utils/index.ts
  pages/event/[code].tsx
  pages/login.tsx
  pages/mypage.tsx
  src/domains/EventList/index.tsx
  src/domains/GiftList.tsx/index.tsx
  src/types/event.d.ts
  src/types/gift.d.ts
Labels: 리뷰 요청, Feat

#60 [GD-180] feat: 이벤트 생성 성공 페이지
  public/roudolf.png
  src/domains/EventComplete/index.tsx
Labels: 리뷰 요청, Feat

#58 [GD-165] feat: 선착순 선물 받기 페이지 - 선물 수령 API 기능 구현
  pages/api/event.ts
  pages/api/utils/index.ts
  pages/fifo/[url].tsx
  pages/login.tsx
  src/components/MUIButton/index.tsx
  src/hooks/useInterval.ts
  src/hooks/useIntervalFn.ts
Labels: Feat, 피드백 반영 && 리뷰 재요청

#62 [GD-191] feat: dotenv 라이브러리 설치 및 Nest.JS env 설정
  .env
  package.json
  pages/api/event.ts
  pages/api/utils/index.ts
  pages/login.tsx
  yarn.lock
Labels: Feat

#63 [GD-182] feat: event detail 조회 및 삭제 api 연동, gift detail 조회 및 수정 api 연동, 로그아웃 버튼 구현
  pages/api/event.ts
  pages/api/gift.ts
  pages/api/services/event.ts
  pages/api/services/gift.ts
  pages/api/user.ts
  pages/event/[code].tsx
  pages/gift/[id].tsx
  pages/index.tsx
  pages/mypage.tsx
  src/components/MUISwitch/index.tsx
  src/components/Spinner/index.tsx
  src/components/Swalert/index.tsx
  src/domains/EventDetail/Cover.tsx
  src/domains/EventDetail/TimeInfo.tsx
  src/domains/EventDetail/WinnerModal.tsx
  src/domains/EventList/index.tsx
  src/domains/GiftList.tsx/index.tsx
  src/types/event.d.ts
  src/types/gift.d.ts
  src/utils/constants/icons.ts
  src/utils/logOut.ts
Labels: Feat

#64 [GD-192] feat: 선물 수령 API 예외처리 추가 및 API 라우터 변경
  pages/api/event.ts
  pages/fifo/[url].tsx
Labels: Feat

#61 [GD-178] feat: 랜덤 선물 받기 페이지 API 연동
  pages/api/event.ts
  pages/random/[url].tsx
  src/domains/CardFlip/index.tsx
  src/domains/IsOverEvent/index.tsx
  src/hooks/useDebounce.ts
  src/hooks/useTimeoutFn.ts
Labels: Feat

#65 [GD-195] refactor: TimerHeader 컴포넌트 message prop 추가
  pages/fifo/[url].tsx
  pages/random/[url].tsx
  src/domains/CardFlip/index.tsx
  src/domains/TimerHeader/index.tsx
Labels: Refactor

#67 [GD-199] feat: 커스텀 404 페이지 추가
  pages/404.tsx
  public/404.png
Labels: Feat

#69 [GD-201] hotfix: 선물 사용여부 api 요청 관련 이슈 해결
  pages/api/gift.ts
  pages/gift/[id].tsx
  src/components/MUISwitch/index.tsx
  src/domains/GiftItem/index.tsx
Labels: Fix

#70 [GD-203] refactor: SweetAlert2 컴포넌트 확장 및 변경된 Alert 적용
  pages/fifo/[url].tsx
  pages/mypage.tsx
  pages/post.tsx
  pages/random/[url].tsx
  public/erroralert.png
  public/giftget.png
  public/logout.png
  src/components/Swalert/ErrorAlert.tsx
  src/components/Swalert/GiftGetAlert.tsx
  src/components/Swalert/LogOutAlert.tsx
  src/components/Swalert/index.tsx
  src/domains/EventPresent/index.tsx
Labels: 리뷰 요청, Refactor

#72 [GD-205] fix: 이벤트 당첨자 목록 조회 api 이슈 해결
  pages/api/event.ts
  pages/api/services/event.ts
  pages/event/[code].tsx
  public/templates/template1.png
  public/templates/template2.png
  public/templates/template3.png
  public/templates/template4.png
  public/templates/template5.png
  public/templates/template6.png
  public/templates/template7.png
  public/templates/template8.png
  public/templates/template9.png
  src/components/Modal/index.tsx
  src/domains/EventDetail/Cover.tsx
  src/domains/EventDetail/TimeInfo.tsx
  src/domains/EventDetail/WinnerModal.tsx
  src/domains/EventList/index.tsx
Labels: 리뷰 요청, Fix

#74 [GD-204] refactor: 선물 등록페이지 전체 CSS 및 레이아웃 수정
  pages/post.tsx
  src/components/Input/InputText.tsx
  src/domains/EventPresent/index.tsx
  src/domains/EventTitle/index.tsx
  src/domains/EventType/index.tsx
  src/domains/TextLabel/index.tsx
Labels: Refactor

#75 [GD-170] feat: 마이페이지 탭 리스트 무한스크롤 적용
  pages/api/event.ts
  pages/api/gift.ts
  pages/api/services/event.ts
  pages/api/services/gift.ts
  pages/mypage.tsx
  src/domains/GiftList.tsx/index.tsx
  src/hooks/useInfiniteScroll.tsx
Labels: 리뷰 요청, Feat

#77 [GD-207] style: Main 페이지 텍스트 인터렉션 5초 변경
  pages/index.tsx
Labels: Style

#76 [GD-206] feat: filter 쿼리를 통해 필터칩 초기화하도록 수정
  package.json
  pages/event/[code].tsx
  pages/gift/[id].tsx
  pages/mypage.tsx
  src/domains/EventList/index.tsx
  src/domains/GiftList.tsx/index.tsx
  yarn.lock
Labels: 리뷰 요청, Feat

#78 [GD-208] style: post페이지 style 수정
  pages/post.tsx
  public/gifts/gift1.png
  public/gifts/gift2.png
  public/gifts/gift3.png
  public/gifts/gift4.png
  public/gifts/gift5.png
  public/gifts/gift6.png
  public/gifts/gift7.png
  public/gifts/gift8.png
  src/components/Input/InputText.tsx
  src/domains/EventPresent/GiftForm.tsx
  src/domains/EventPresent/PresentModal.tsx
  src/domains/EventPresent/index.tsx
  src/domains/EventTimer/index.tsx
  src/domains/EventTitle/index.tsx
  src/domains/EventType/index.tsx
Labels: Style

#80 [GD-209] fix: 랜덤 페이지 선물 카드 zindex 수정 및 CardFlip 버튼 텍스트 수정
  pages/random/[url].tsx
  src/domains/CardFlip/index.tsx
Labels: Fix

#79 [GD-182] feat: 이벤트 종료에 따른 당첨자 목록 처리
  pages/api/services/event.ts
  pages/event/[code].tsx
  src/components/Swalert/RemoveAlert.tsx
  src/components/Swalert/index.tsx
  src/domains/EventDetail/Cover.tsx
  src/domains/EventDetail/WinnerModal.tsx
  src/types/event.d.ts
Labels: Feat, Refactor, Fix

#82 [GD-210] refactor: Random 페이지 꽝 수령시 선물 당첨 이벤트 실행
  pages/random/[url].tsx
  public/boom.png
  public/card1.png
  src/domains/CardFlip/index.tsx
  src/types/gift.d.ts
Labels: 리뷰 요청, Refactor

#83 [GD-211] refactor: 선착순 페이지 정적이미지 교체
  pages/fifo/[url].tsx
Labels: 리뷰 요청, Refactor

#81 [GD-175] feat: 뒤로 가기 버튼 추가 및 로직 개선
  pages/post.tsx
  src/components/Textarea/index.tsx
  src/domains/EventPresent/PresentModal.tsx
  src/domains/EventPresent/index.tsx
Labels: Feat, Style, Chore

#84 style: 폰트 수정
  pages/_app.tsx
  src/components/Text/index.tsx
  styles/globals.css
Labels: Style

#85 [GD-212] feat: 텍스트, 꽝 png 파일로 변환 및 다운로드 기능 추가
  pages/random/[url].tsx
  src/domains/CardFlip/index.tsx
Labels: 리뷰 요청, Feat

#86 style: 이벤트 디테일 페이지 당첨자 모달
  pages/event/[code].tsx
  pages/mypage.tsx
  public/empty.png
  src/domains/EventDetail/Cover.tsx
  src/domains/EventDetail/TimeInfo.tsx
  src/domains/EventDetail/WinnerModal.tsx
  src/domains/EventList/index.tsx
  src/domains/GiftList.tsx/index.tsx
  src/domains/Header/index.tsx
Labels: 리뷰 요청, Style

#87 [GD-147] feat: 선물 등록 모달 더보기 버튼 구현
  src/components/Text/index.tsx
  src/domains/EventPresent/PresentModal.tsx
Labels: 리뷰 요청, Feat

#89 hotfix: 누락된 props 추가
  pages/event/[code].tsx
  src/domains/Header/index.tsx
Labels: Fix

#95 [GD-215] fix: 타이머, 헤더 얼럿 CSS 수정
  pages/fifo/[url].tsx
  src/components/Swalert/ErrorAlert.tsx
  src/components/Swalert/GiftGetAlert.tsx
  src/domains/TimerHeader/index.tsx
Labels: 리뷰 요청, Fix

#98 [GD-220] refactor: API 변경에 따른 Soldout 로직 변경
  pages/fifo/[url].tsx
Labels: Refactor

#100 [GD-222] fix: 선물 받기 버튼 width 개선
  src/domains/CardFlip/index.tsx
Labels: Fix

#102 [GD-223] fix: 선착순,랜덤 랜더링 개선& 스피너 추가&오타수정
  pages/api/user.ts
  pages/event/[code].tsx
  pages/fifo/[url].tsx
  pages/gift/[id].tsx
  pages/index.tsx
  pages/mypage.tsx
  pages/post.tsx
  pages/random/[url].tsx
  src/domains/GiftList/index.tsx
Labels: Fix

#103 [GD-224] fix: user-select 속성 적용
  pages/index.tsx
  pages/login.tsx
  pages/mypage.tsx
  src/components/Modal/index.tsx
  src/domains/EventDetail/WinnerModal.tsx
  src/domains/Header/index.tsx
  src/domains/TimerHeader/index.tsx
Labels: Fix

#104 [GD-218] fix: stepper css 수정 및 간단한 수정
  pages/fifo/[url].tsx
  pages/random/[url].tsx
  styles/globals.css
Labels: Feat, Chore

#105 [GD-226] style: 이벤트 등록페이지 레이아웃 및 css 수정
  pages/post.tsx
  public/event_type.png
  src/components/Textarea/index.tsx
  src/domains/EventPresent/GiftForm.tsx
  src/domains/EventPresent/PresentModal.tsx
  src/domains/EventPresent/index.tsx
  src/domains/EventTitle/index.tsx
  src/domains/EventType/index.tsx
  src/domains/TextLabel/index.tsx
Labels: Style

#107 style: 이벤트 디테일 페이지 및 이벤트 등록 페이지 스타일 수정
  public/event_type.png
  src/domains/EventDetail/Cover.tsx
  src/domains/EventPresent/PresentModal.tsx
Labels: Style

#115 [GD-228] Hotfix 2.1.3
  pages/fifo/[url].tsx
Labels: 리뷰 요청, Hotfix

#116 Hotfix 2.1.3
  pages/fifo/[url].tsx
Labels: Hotfix
